// Lazy-access to the vendored Game Genie cheat database (generated by ingest.py from
// references/Game Genie Code Compilation - Shared.xlsx). The JSON is fetched as a Vite
// asset on first use (code-split, gzipped at serve) so it never bloats the main bundle.
import cheatsUrl from "./cheats.json?url";

export interface Cheat {
  /** Game Genie code, or multiple joined with " + ". */
  code: string;
  effect: string;
}
export interface CheatGame {
  title: string;
  /** Normalized match key (see normalizeTitle). */
  key: string;
  cheats: Cheat[];
}
export interface CheatDB {
  meta: { source: string; note: string; counts: Record<string, { games: number; codes: number }> };
  /** Keyed by system: nes | snes | gb | genesis | gamegear. */
  systems: Record<string, CheatGame[]>;
}

let cache: CheatDB | null = null;

/** Load the cheat database (cached after first fetch). */
export async function loadCheats(): Promise<CheatDB> {
  if (!cache) cache = (await (await fetch(cheatsUrl)).json()) as CheatDB;
  return cache;
}

/** Normalize a ROM/game title to the database's match key — must mirror ingest.py's norm(). */
export function normalizeTitle(title: string): string {
  return title
    .replace(/\([^)]*\)/g, "") // drop (USA), (Rev 1), …
    .toLowerCase()
    .replace(/^(the|a)\s+/, "")
    .replace(/[^a-z0-9]/g, "");
}

/** Find the cheat entry for a game title within a system (exact normalized-key match). A
 *  fuzzier match (Levenshtein/substring) can layer on top later. */
export function findGameCheats(db: CheatDB, system: string, title: string): CheatGame | null {
  const list = db.systems[system];
  if (!list) return null;
  const key = normalizeTitle(title);
  return list.find((g) => g.key === key) ?? null;
}
