// Lazy-access to the vendored Game Genie cheat database (generated by ingest.py from
// references/Game Genie Code Compilation - Shared.xlsx). One JSON file PER SYSTEM
// (nes.json, gb.json, …), fetched as a Vite asset only for the system actually being
// viewed — NES alone is 330KB+; shipping all five systems' data (nes/snes/gb/genesis/
// gamegear) in one 1.8MB file regardless of which (or whether any) system the user is
// looking at was pure waste, especially since SNES/Genesis/GameGear have no firmware
// cheat support at all (see lineCheatSystems in GameDetailsPanel.svelte) and their data
// was never even used.
import mcfManifestJson from "./mcfManifest.json";
import { dbg } from "../debug.js";

const SYSTEM_URLS: Record<string, () => Promise<{ default: string }>> = {
  nes: () => import("./nes.json?url"),
  snes: () => import("./snes.json?url"),
  gb: () => import("./gb.json?url"),
  genesis: () => import("./genesis.json?url"),
  gamegear: () => import("./gamegear.json?url"),
};

// --- MCF whole-file presets (blueMSX-family cheat files) ---------------------------------
// Per the firmware README (game-and-watch-retro-go-sd), MSX/Coleco/SG-1000 (blueMSX-go core)
// consume cheats as a WHOLE FILE copied verbatim into cheats/<system>/<name>.mcf — not a list
// of individually toggleable codes like NES/GB's .ggcodes. The project root's cheat-codes/
// folder (mirrored as static assets at apps/web/public/cheat-codes/<sourceDir>/*.mcf, built by
// the manifest below) holds ~900 MSX + a handful of Coleco/SG-1000/SVI files, keyed by a
// filename that's already lowercase/alnum-only — matches normalizeTitle()'s convention.
// SVI has no corresponding system in this app's retro-go fork (no SVI core built) so it's kept
// in the manifest (harmless) but never wired to a UI system id below.
export const MCF_WHOLE_FILE_SYSTEMS: Record<string, string> = {
  msx: "msx",
  col: "coleco", // ColecoVision
  sg1000: "sega", // Sega SG-1000
};
const mcfManifest = mcfManifestJson as Record<string, string[]>;
// Precomputed normalized-name -> original-basename lookup per source dir, built lazily once.
let mcfIndex: Record<string, Map<string, string>> | null = null;
function getMcfIndex(): Record<string, Map<string, string>> {
  if (!mcfIndex) {
    mcfIndex = {};
    for (const [dir, names] of Object.entries(mcfManifest)) {
      const map = new Map<string, string>();
      for (const name of names) map.set(normalizeTitle(name), name);
      mcfIndex[dir] = map;
    }
  }
  return mcfIndex;
}

/** Find a built-in MCF cheat file for `title` in the given app system id (e.g. "msx", "col",
 *  "sg1000"). Returns the exact on-disk basename (no extension) to fetch via mcfAssetUrl, or
 *  null if this system has no MCF source or no match. */
export function findMcfPreset(system: string, title: string): string | null {
  const dir = MCF_WHOLE_FILE_SYSTEMS[system];
  if (!dir) return null;
  const map = getMcfIndex()[dir];
  if (!map) return null;
  return map.get(normalizeTitle(title)) ?? null;
}

/** URL to fetch a built-in MCF file's raw bytes (served as a static asset). */
export function mcfAssetUrl(system: string, basename: string): string {
  const dir = MCF_WHOLE_FILE_SYSTEMS[system];
  return `/cheat-codes/${dir}/${basename}.mcf`;
}

export interface Cheat {
  /** Game Genie code, or multiple joined with " + ". */
  code: string;
  effect: string;
}
export interface CheatGame {
  title: string;
  /** Normalized match key (see normalizeTitle). */
  key: string;
  cheats: Cheat[];
}

const cache: Partial<Record<string, CheatGame[]>> = {};

/**
 * Systems the firmware applies cheats for that have NO preset database, so an empty list is the
 * correct answer rather than a fault. PCE's `.pceplus` files are raw memory patches and no
 * source of them exists anywhere; libretro-database's PCE `.cht` files are RetroArch's own
 * `address:value` format and are not convertible without reverse-engineering the firmware's
 * bit-packing. See the cheats-system-rework note.
 *
 * Naming it here is what makes the difference between a known gap and a typo: `loadCheatsForSystem`
 * returns [] either way, and a mistyped key used to be indistinguishable from this.
 */
export const CHEAT_SYSTEMS_WITHOUT_DATABASE = new Set(["pce"]);

/** Load one system's cheat list (cached after first fetch). Returns [] for a system with no
 *  database. Takes the DATABASE name, which is not the app's system id: a `.gbc` game has
 *  system id "gbc" and reads gb.json, and the translation is GameDetailsPanel's
 *  `lineCheatSystems`. Passing a raw system id here is the mistake to watch for. */
export async function loadCheatsForSystem(system: string): Promise<CheatGame[]> {
  if (cache[system]) return cache[system]!;
  const load = SYSTEM_URLS[system];
  if (!load) {
    if (!CHEAT_SYSTEMS_WITHOUT_DATABASE.has(system)) {
      dbg(`[cheats] no database named ${JSON.stringify(system)}; known: ${Object.keys(SYSTEM_URLS).join(", ")}`);
    }
    return (cache[system] = []);
  }
  const { default: url } = await load();
  const games = (await (await fetch(url)).json()) as CheatGame[];
  return (cache[system] = games);
}

/** Normalize a ROM/game title to the database's match key — must mirror ingest.py's norm().
 *  Do NOT change this in isolation: the per-system JSON keys are generated by ingest.py with
 *  the identical rule, so any edit here silently desyncs every key in the database. Filename
 *  quirks belong in the ladder below, which normalizes the FILENAME side only. */
export function normalizeTitle(title: string): string {
  return title
    .replace(/\([^)]*\)/g, "") // drop (USA), (Rev 1), …
    .toLowerCase()
    .replace(/^(the|a)\s+/, "")
    .replace(/[^a-z0-9]/g, "");
}

/** Strip a ROM filename down to a title: drop the extension, the parenthesised No-Intro tags
 *  and the square-bracket GoodTools tags (`[!]`, `[b1]`). Parens are dropped by normalizeTitle
 *  too, but the article rule below has to see the bare title or "(USA, Europe)"'s comma looks
 *  like an inverted article. */
function titleFromFilename(filename: string): string {
  return filename
    .replace(/\.[^/.]+$/, "")
    .replace(/\([^)]*\)/g, "")
    .replace(/\[[^\]]*\]/g, "")
    .trim();
}

/** Undo the No-Intro inverted article: "Legend of Zelda, The - Link's Awakening DX" becomes
 *  "The Legend of Zelda - Link's Awakening DX". The article moves to the end of the FIRST
 *  title segment, not the end of the whole string, which is why the trailing " - …" has to be
 *  carried over rather than matched away. Returns null when there is no inverted article.
 *
 *  This is the single most common filename shape in a real ROM set and the database stores the
 *  uninverted form, so without it every article title misses: 46 of 757 GB entries and 47 of
 *  721 NES entries were unreachable. */
function uninvertArticle(title: string): string | null {
  const m = /^(.*?),\s*(The|A|An)\b(\s+-\s+.*)?$/i.exec(title);
  if (!m) return null;
  return `${m[2]} ${m[1]}${m[3] ?? ""}`;
}

/** Shortest normalized key the containment rung will consider. Below this a key is so short
 *  that being a substring says nothing (a three-letter title appears inside many names). */
const MIN_CONTAINMENT_LEN = 4;

/** Which rung of the ladder produced a match. Exposed so a caller (and the suite) can tell a
 *  certain match from an inferred one without re-deriving it. */
export type CheatMatchVia = "exact" | "article" | "contains";
export interface CheatMatch {
  game: CheatGame;
  via: CheatMatchVia;
}

/**
 * Resolve a ROM filename to its cheat database entry, most reliable rung first. The owner's
 * rule for the cover lookup, applied here: go down the list of reliability until something
 * answers, and let absent stay absent.
 *
 *   1. exact    — the normalized filename IS a database key. Certain.
 *   2. article  — same, after undoing a No-Intro inverted article.
 *   3. contains — the normalized filename sits inside exactly ONE key, or exactly one key sits
 *                 inside it. This is what reaches a short or subtitle-only filename such as
 *                 "Link's Awakening DX.gbc".
 *
 * **Uniqueness is the safety property on rung 3, not a nicety.** The pre-overhaul matcher was
 * a bidirectional substring scan that returned the FIRST title it touched, and measured against
 * this same database it picked the wrong game for 253 of 1514 GB names and 230 of 1442 NES
 * names on ordinary "title (Region)" filenames. Refusing an ambiguous match rather than
 * guessing is the whole difference. A game the ladder cannot place is left unmatched for the
 * user to pick by hand, which the panel already supports.
 */
export function resolveCheatGame(
  games: Map<string, CheatGame>,
  filename: string,
): CheatMatch | null {
  const title = titleFromFilename(filename);

  const exact = games.get(normalizeTitle(title));
  if (exact) return { game: exact, via: "exact" };

  const uninverted = uninvertArticle(title);
  if (uninverted) {
    const hit = games.get(normalizeTitle(uninverted));
    if (hit) return { game: hit, via: "article" };
  }

  const key = normalizeTitle(title);
  if (key.length < MIN_CONTAINMENT_LEN) return null;
  let found: CheatGame | null = null;
  for (const game of games.values()) {
    const k = game.key;
    if (!(key.includes(k) && k.length >= MIN_CONTAINMENT_LEN) && !k.includes(key)) continue;
    if (found) return null; // ambiguous — refuse rather than pick one
    found = game;
  }
  return found ? { game: found, via: "contains" } : null;
}
