// Lazy-access to the vendored Game Genie cheat database (generated by ingest.py from
// references/Game Genie Code Compilation - Shared.xlsx). One JSON file PER SYSTEM
// (nes.json, gb.json, …), fetched as a Vite asset only for the system actually being
// viewed — NES alone is 330KB+; shipping all five systems' data (nes/snes/gb/genesis/
// gamegear) in one 1.8MB file regardless of which (or whether any) system the user is
// looking at was pure waste, especially since SNES/Genesis/GameGear have no firmware
// cheat support at all (see lineCheatSystems in GameDetailsPanel.svelte) and their data
// was never even used.
import mcfManifestJson from "./mcfManifest.json";

const SYSTEM_URLS: Record<string, () => Promise<{ default: string }>> = {
  nes: () => import("./nes.json?url"),
  snes: () => import("./snes.json?url"),
  gb: () => import("./gb.json?url"),
  genesis: () => import("./genesis.json?url"),
  gamegear: () => import("./gamegear.json?url"),
};

// --- MCF whole-file presets (blueMSX-family cheat files) ---------------------------------
// Per the firmware README (game-and-watch-retro-go-sd), MSX/Coleco/SG-1000 (blueMSX-go core)
// consume cheats as a WHOLE FILE copied verbatim into cheats/<system>/<name>.mcf — not a list
// of individually toggleable codes like NES/GB's .ggcodes. The project root's cheat-codes/
// folder (mirrored as static assets at apps/web/public/cheat-codes/<sourceDir>/*.mcf, built by
// the manifest below) holds ~900 MSX + a handful of Coleco/SG-1000/SVI files, keyed by a
// filename that's already lowercase/alnum-only — matches normalizeTitle()'s convention.
// SVI has no corresponding system in this app's retro-go fork (no SVI core built) so it's kept
// in the manifest (harmless) but never wired to a UI system id below.
export const MCF_WHOLE_FILE_SYSTEMS: Record<string, string> = {
  msx: "msx",
  col: "coleco", // ColecoVision
  sg1000: "sega", // Sega SG-1000
};
const mcfManifest = mcfManifestJson as Record<string, string[]>;
// Precomputed normalized-name -> original-basename lookup per source dir, built lazily once.
let mcfIndex: Record<string, Map<string, string>> | null = null;
function getMcfIndex(): Record<string, Map<string, string>> {
  if (!mcfIndex) {
    mcfIndex = {};
    for (const [dir, names] of Object.entries(mcfManifest)) {
      const map = new Map<string, string>();
      for (const name of names) map.set(normalizeTitle(name), name);
      mcfIndex[dir] = map;
    }
  }
  return mcfIndex;
}

/** Find a built-in MCF cheat file for `title` in the given app system id (e.g. "msx", "col",
 *  "sg1000"). Returns the exact on-disk basename (no extension) to fetch via mcfAssetUrl, or
 *  null if this system has no MCF source or no match. */
export function findMcfPreset(system: string, title: string): string | null {
  const dir = MCF_WHOLE_FILE_SYSTEMS[system];
  if (!dir) return null;
  const map = getMcfIndex()[dir];
  if (!map) return null;
  return map.get(normalizeTitle(title)) ?? null;
}

/** URL to fetch a built-in MCF file's raw bytes (served as a static asset). */
export function mcfAssetUrl(system: string, basename: string): string {
  const dir = MCF_WHOLE_FILE_SYSTEMS[system];
  return `/cheat-codes/${dir}/${basename}.mcf`;
}

export interface Cheat {
  /** Game Genie code, or multiple joined with " + ". */
  code: string;
  effect: string;
}
export interface CheatGame {
  title: string;
  /** Normalized match key (see normalizeTitle). */
  key: string;
  cheats: Cheat[];
}

const cache: Partial<Record<string, CheatGame[]>> = {};

/** Load one system's cheat list (cached after first fetch). Returns [] for a system with
 *  no database (e.g. "pce" — no source data exists). */
export async function loadCheatsForSystem(system: string): Promise<CheatGame[]> {
  if (cache[system]) return cache[system]!;
  const load = SYSTEM_URLS[system];
  if (!load) return (cache[system] = []);
  const { default: url } = await load();
  const games = (await (await fetch(url)).json()) as CheatGame[];
  return (cache[system] = games);
}

/** Normalize a ROM/game title to the database's match key — must mirror ingest.py's norm(). */
export function normalizeTitle(title: string): string {
  return title
    .replace(/\([^)]*\)/g, "") // drop (USA), (Rev 1), …
    .toLowerCase()
    .replace(/^(the|a)\s+/, "")
    .replace(/[^a-z0-9]/g, "");
}

/** Find the cheat entry for a game title within a system's already-loaded list (exact
 *  normalized-key match). A fuzzier match (Levenshtein/substring) can layer on top later. */
export function findGameCheats(games: CheatGame[], title: string): CheatGame | null {
  const key = normalizeTitle(title);
  return games.find((g) => g.key === key) ?? null;
}
