#!/usr/bin/env python3
"""Ingest the Game Genie xlsx into cheats.json for the web app. Stdlib only.
Re-run: python3 apps/web/src/lib/cheats/ingest.py"""
import zipfile, xml.etree.ElementTree as ET, re, json, os
NS='{http://schemas.openxmlformats.org/spreadsheetml/2006/main}'
RNS='{http://schemas.openxmlformats.org/officeDocument/2006/relationships}'
SRC="references/Game Genie Code Compilation - Shared.xlsx"
OUT_DIR="apps/web/src/lib/cheats"
META_OUT=f"{OUT_DIR}/cheatsMeta.json"
SYS={'NES':'nes','SNES':'snes','Game Boy':'gb','Genesis':'genesis','Game Gear':'gamegear'}
CODE=re.compile(r'[A-Z0-9]+([ +\-]+[A-Z0-9]+)*')  # uppercase GG code(s); rejects note rows
z=zipfile.ZipFile(SRC)
ss=[''.join(t.text or '' for t in si.iter(f'{NS}t')) for si in ET.fromstring(z.read('xl/sharedStrings.xml')).findall(f'{NS}si')]
sheets=[(s.get('name'),s.get(f'{RNS}id')) for s in ET.fromstring(z.read('xl/workbook.xml')).find(f'{NS}sheets')]
rid2t={r.get('Id'):r.get('Target') for r in ET.fromstring(z.read('xl/_rels/workbook.xml.rels'))}
n2f={n:('xl/'+rid2t[r].lstrip('/')).replace('xl/xl/','xl/') for n,r in sheets if r in rid2t}
def rows(name):
    sd=ET.fromstring(z.read(n2f[name])).find(f'{NS}sheetData')
    for row in sd.findall(f'{NS}row'):
        d={}
        for c in row.findall(f'{NS}c'):
            v=c.find(f'{NS}v'); cl=re.match(r'[A-Z]+',c.get('r')).group()
            d[cl]=(ss[int(v.text)] if (v is not None and c.get('t')=='s') else (v.text if v is not None else '')).strip()
        yield d
def norm(t):
    t=re.sub(r'\([^)]*\)','',t).lower()
    t=re.sub(r'^(the|a)\s+','',t)
    return re.sub(r'[^a-z0-9]','',t)
db={}; counts={}; skipped={}
for disp,key in SYS.items():
    ccol=ecol=None; gcol='A'; games={}; skip=0
    for r in rows(disp):
        if ccol is None:                                   # find header row by "Key in…"
            ki=[cl for cl,t in r.items() if t.startswith('Key in')]
            if ki:
                ccol=ki[0]; ef=[cl for cl,t in r.items() if t.startswith('Effect')]; ecol=ef[0] if ef else None
            continue
        g=r.get(gcol,'').strip(); code=re.sub(r'\s+',' ',r.get(ccol,'').strip())
        eff=r.get(ecol,'').strip() if ecol else ''
        if not g or not code: continue
        if not CODE.fullmatch(code): skip+=1; continue     # drop note/free-text rows
        games.setdefault(g,[]).append({'code':code,'effect':eff})
    db[key]=[{'title':g,'key':norm(g),'cheats':c} for g,c in games.items()]
    counts[key]={'games':len(db[key]),'codes':sum(len(x['cheats']) for x in db[key])}; skipped[key]=skip

# One JSON per system (apps/web/src/lib/cheats/<system>.json), lazily fetched only when that
# system's cheats panel is actually opened — NES/SNES/GB/Genesis/GameGear ranged 100KB-730KB
# each; shipping/fetching all of them in one 1.8MB cheats.json regardless of which system (or
# whether any at all — SNES/Genesis/GameGear have no firmware cheat support, see the app's
# lineCheatSystems) the user is looking at was pure waste.
bytes_out={}
for key,games in db.items():
    path=f"{OUT_DIR}/{key}.json"
    json.dump(games,open(path,'w'),ensure_ascii=False,separators=(',',':'))
    bytes_out[key]=os.path.getsize(path)
meta={'source':os.path.basename(SRC),'note':'Game Genie codes; generated by ingest.py; one file per system, see cheatsMeta.json','counts':counts}
json.dump(meta,open(META_OUT,'w'),ensure_ascii=False,indent=2)
print('counts:',json.dumps(counts)); print('skipped(non-code rows):',json.dumps(skipped)); print('bytes per system:',json.dumps(bytes_out))
def find(s,k): return next((x for x in db[s] if x['key']==k),None)
for s,k in [('nes','supermariobros'),('gamegear','addamsfamily'),('snes','supermarioworld')]:
    g=find(s,k); print(s,k,'->',(g['title'],len(g['cheats']),g['cheats'][0]) if g else None)
