#!/usr/bin/env node
// Runs measure.sh (needs dosfstools + exfatprogs installed in the container --
// see docs/SDCARD_CAPACITY.md), reshapes its raw per-(size,filesystem) rows
// into the JSON the app imports, and writes it out.
//
// Usage (inside the dev container):
//   node scripts/sdcapacity/generate.mjs > apps/web/src/lib/data/sdCapacity.json
//
// Or, to reshape an already-captured raw measurement (e.g. to avoid
// re-running mkfs/dosfstools):
//   bash scripts/sdcapacity/measure.sh > /tmp/raw.json
//   node scripts/sdcapacity/generate.mjs --raw /tmp/raw.json > apps/web/src/lib/data/sdCapacity.json

import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));

// The app subtracts this from the usable figure so a sync can never overrun
// the card. Kept as its own field (see docs/SDCARD_CAPACITY.md) so it can be
// tuned without re-measuring anything.
const SAFETY_MARGIN_BYTES = 100 * 1024 * 1024; // 100 MiB

function getRawRows() {
  const rawArgIndex = process.argv.indexOf("--raw");
  if (rawArgIndex !== -1) {
    const path = process.argv[rawArgIndex + 1];
    return JSON.parse(readFileSync(path, "utf8"));
  }
  const script = join(__dirname, "measure.sh");
  const out = execFileSync("bash", [script], { maxBuffer: 64 * 1024 * 1024 });
  return JSON.parse(out.toString("utf8"));
}

const rows = getRawRows();

const bySize = new Map();
for (const row of rows) {
  if (!bySize.has(row.nominalGB)) {
    bySize.set(row.nominalGB, {
      nominalGB: row.nominalGB,
      nominalBytes: row.nominalBytes,
      partitionAlignmentBytes: row.partitionAlignmentBytes,
      usableAfterPartitionBytes: row.usableAfterPartitionBytes,
      filesystems: {},
    });
  }
  const entry = bySize.get(row.nominalGB);
  entry.filesystems[row.filesystem] = {
    clusterSizeBytes: row.clusterSizeBytes,
    usableBytes: row.usableBytes,
    usableAfterMarginBytes: row.usableBytes - SAFETY_MARGIN_BYTES,
  };
}

const sizes = [...bySize.values()].sort((a, b) => a.nominalGB - b.nominalGB);

const output = {
  $schemaNote:
    "Generated by scripts/sdcapacity/generate.mjs from scripts/sdcapacity/measure.sh. See docs/SDCARD_CAPACITY.md.",
  method: "measured",
  measuredWith: "dosfstools mkfs.vfat/fsck.fat + exfatprogs mkfs.exfat/dump.exfat, Debian bookworm",
  nominalByteConvention: "1 GB = 1,000,000,000 bytes (decimal, matches card label / SD Association convention)",
  partitionAlignmentBytes: 4 * 1024 * 1024,
  safetyMarginBytes: SAFETY_MARGIN_BYTES,
  sizes,
};

process.stdout.write(JSON.stringify(output, null, 2) + "\n");
