/**
 * HOW BIG THE CARD IS -- stated by the user, because the browser cannot be asked.
 *
 * WHY THIS IS A SEPARATE MODULE FROM `sdStorage.svelte.ts`, and why that matters.
 * That module measures, and its contract is that it never invents a denominator: a
 * `FileSystemDirectoryHandle` does not expose the volume it came from, and
 * `navigator.storage.estimate()` is the plausible wrong answer (it reports this ORIGIN's quota,
 * a real number about the browser profile that has nothing to do with the card).
 * `apps/web/test/sdstorage.mjs` pins that as NEGATIVE assertions -- no `capacity`, no free-space
 * figure, and one total that is the sum of the buckets. Putting a stated size in that file would
 * break those guards, and it should: the two numbers have different provenance and a reader who
 * cannot tell them apart is exactly what the guards exist to prevent.
 *
 * So: used bytes are MEASURED over there, the card's size is STATED here, and nothing in this
 * module walks anything or pretends to detect a capacity.
 *
 * WHERE THE FIGURES COME FROM. `data/sdCapacity.json` is generated by
 * `scripts/sdcapacity/measure.sh`, which formats a sparse image at each nominal size with real
 * `mkfs.vfat` / `mkfs.exfat` and reads the usable space back with `fsck.fat -n -v` /
 * `dump.exfat`. They are measured, not computed from the specifications. `docs/SDCARD_CAPACITY.md`
 * records the method and its error bars.
 *
 * THE STATED SIZE IS OPTIONAL, and the unset state is first class. No stated size means no
 * denominator, and every reader has to work without one -- which is the state the app was in
 * before this module existed, so it is the well-trodden path rather than the edge.
 *
 * THE USER IS NOT ASKED WHICH FILESYSTEM, and the measured table is why. exFAT's usable space
 * exceeds FAT32's by 1.7 MB at 2 GB, 12.4 MB at 16 GB and 52.7 MB at 256 GB -- every one of
 * them smaller than the 100 MB margin already withheld. So the answer could not change the
 * figure, and asking would have been a question with no consequence. The per-filesystem rows
 * STAY in `data/sdCapacity.json`: they are the measurement that proves this, and
 * `docs/SDCARD_CAPACITY.md` reads them. The app simply stops asking, and every figure below
 * takes the conservative side of the pair.
 */
import raw from "./data/sdCapacity.json";
import { loadSel, saveSel } from "./persist.js";

/**
 * The filesystems the table measured. NOT a user-facing choice: this names the columns of the
 * evidence, and the functions below reduce over them rather than selecting one.
 */
type SdFilesystem = "fat32" | "exfat";

const MEASURED_FILESYSTEMS: readonly SdFilesystem[] = ["fat32", "exfat"];

interface FsRow {
  clusterSizeBytes: number;
  usableBytes: number;
  usableAfterMarginBytes: number;
}
interface SizeRow {
  nominalGB: number;
  nominalBytes: number;
  partitionAlignmentBytes: number;
  usableAfterPartitionBytes: number;
  filesystems: Record<SdFilesystem, FsRow>;
}
interface CapacityTable {
  safetyMarginBytes: number;
  sizes: SizeRow[];
}

const TABLE = raw as unknown as CapacityTable;

/**
 * The safety margin, held apart from the capacities on purpose.
 *
 * The owner asked for "roughly 100 MB lobbed off" so a sync cannot overrun the card. Keeping it
 * as its own field rather than baked into the figures means it can be retuned without
 * regenerating anything, and a reader can always recover the raw measurement.
 *
 * It is NOT uniform in proportion: about 5.3% of a 2 GB card and about 0.04% of a 256 GB one.
 * That is recorded in `docs/SDCARD_CAPACITY.md`; whether the small end wants a percentage with
 * a floor instead is a product decision, not arithmetic, and has not been made.
 */
export const SAFETY_MARGIN_BYTES = TABLE.safetyMarginBytes;

/**
 * The sizes a user can state, smallest first.
 *
 * Powers of two, which is what real cards are and what the table covers. Derived from the table
 * rather than written out, so the list and the figures cannot drift apart.
 */
export const SD_NOMINAL_SIZES_GB: readonly number[] = TABLE.sizes
  .map((s) => s.nominalGB)
  .sort((a, b) => a - b);

function rowFor(nominalGB: number): SizeRow | null {
  return TABLE.sizes.find((s) => s.nominalGB === nominalGB) ?? null;
}

/**
 * Usable bytes for a stated size, after the safety margin.
 *
 * TAKE THE SMALLER OF THE MEASURED PAIR. The owner's rule: "We choose the more conservative of
 * the two FS capacity differences." FAT32 is the lower figure at every size in the table, but
 * this MINIMISES over whatever the table holds rather than hardcoding `fat32` -- if a
 * regenerated table ever inverts at some size, the conservative rule still holds and no caller
 * has to be found and fixed.
 *
 * Returns `null` for a size the table does not cover, so an unknown size is an absent answer
 * rather than a zero that would read as "a full card".
 */
export function usableBytesFor(nominalGB: number): number | null {
  const row = rowFor(nominalGB);
  if (!row) return null;
  const all = MEASURED_FILESYSTEMS.map((f) => row.filesystems[f]?.usableAfterMarginBytes).filter(
    (n): n is number => typeof n === "number",
  );
  return all.length ? Math.min(...all) : null;
}

/**
 * The cluster size for a stated size: the LARGEST of the measured pair.
 *
 * CONSERVATIVE HERE MEANS THE OPPOSITE DIRECTION FROM CAPACITY, and both serve one rule --
 * never promise room the card may not have. Capacity takes the smaller so free space is not
 * overstated; the cluster takes the larger because every file rounds up to a whole one, so a
 * bigger cluster consumes more and a consumption estimate built on the smaller would understate
 * the fill. exFAT uses 128 KiB clusters from 64 GB up while FAT32 stays at 32 KiB, and against a
 * library of small ROMs and covers that difference is worth hundreds of megabytes -- far more
 * than the safety margin withholds.
 *
 * This was `Math.max` over the pair when the filesystem was unknown and is now unconditional,
 * which is the same answer the unknown case always gave: nothing ever stated a filesystem that
 * could have selected the smaller figure.
 */
export function clusterSizeFor(nominalGB: number): number | null {
  const row = rowFor(nominalGB);
  if (!row) return null;
  const all = MEASURED_FILESYSTEMS.map((f) => row.filesystems[f]?.clusterSizeBytes).filter(
    (n): n is number => typeof n === "number",
  );
  return all.length ? Math.max(...all) : null;
}

/**
 * Bytes a set of files really consumes, once each has rounded up to a whole cluster.
 *
 * Raw bytes understate a card's fill, and on a card of many small files they understate it
 * badly. A caller with per-file sizes should use this; a caller with only a bucket total
 * cannot, which is why this takes sizes rather than a sum.
 */
export function bytesOnDisk(fileSizes: Iterable<number>, clusterBytes: number): number {
  if (!(clusterBytes > 0)) return [...fileSizes].reduce((n, s) => n + s, 0);
  let total = 0;
  for (const size of fileSizes) total += Math.ceil(size / clusterBytes) * clusterBytes;
  return total;
}

/**
 * Can the user state this size for a card already holding `usedBytes`?
 *
 * A size below what the walk has ALREADY SEEN is not a preference to disagree with, it is a
 * claim the card has disproved. Refusing it is honest in a way that refusing a guess would not
 * be, because `usedBytes` is measured.
 *
 * A TRUNCATED WALK STILL REFUSES. A truncated total is a floor, and a floor is enough: having
 * seen 3.32 GB proves the card holds at least that, whatever the walk missed. The refusal needs
 * the total to be real, not complete -- so this deliberately takes no `truncated` flag, because
 * there is no branch for it to drive.
 */
export function sizeFitsUsed(nominalGB: number, usedBytes: number): boolean {
  const usable = usableBytesFor(nominalGB);
  return usable === null ? false : usable >= usedBytes;
}

// --- What the user stated, remembered ---------------------------------------------------------

/**
 * The stated size, persisted WITH THE CARD IT WAS STATED FOR.
 *
 * A size remembered for the wrong card is worse than no size at all: it would draw a confident
 * budget against a denominator the user never claimed, and nothing on screen would say so. So
 * the record carries the folder name it was stated for, and a card whose name does not match
 * reads as unset rather than inheriting it.
 *
 * The folder name is a weak identifier -- two cards can share one, and a rename loses the
 * record -- but it is the only identifier a directory handle offers, and both failures are
 * SAFE: the first asks the user to state a size they already stated, the second is a genuine
 * collision between two cards the browser itself cannot tell apart. Neither invents a number.
 *
 * `loadSel`/`saveSel` put this under the `gnw:` namespace, which already goes through
 * `scoped()` in `persist.ts` and is already in `test/storagescope.mjs`'s inventory. A new
 * top-level key would have needed its own inventory entry; riding the namespace needs none.
 */
const STATED_KEY = "sd.stated.v1";

export interface StatedCard {
  /** The folder name this was stated for. See the note above on why it is carried. */
  folderName: string;
  nominalGB: number;
}

/** What the user stated for THIS card, or `null` if nothing applies to it. */
export function loadStatedCard(folderName: string | null | undefined): StatedCard | null {
  if (!folderName) return null;
  const rec = loadSel<StatedCard | null>(STATED_KEY, null);
  if (!rec || rec.folderName !== folderName) return null;
  // A table regenerated without a size the user had stated must not resurrect it as a figure
  // nothing can look up.
  return rowFor(rec.nominalGB) ? rec : null;
}

/** Remember a stated size for this card. Pass `null` to forget it. */
export function saveStatedCard(rec: StatedCard | null): void {
  saveSel(STATED_KEY, rec);
}

/**
 * Bar segments for the card page, as percentages of the CARD, with the sub-pixel floor.
 *
 * WHY A FLOOR AT ALL, AND WHERE ITS COST IS PUT. At nine buckets against a card-sized
 * denominator, seven are under a third of a percent: on a 684px bar that is a fraction of one
 * pixel, and Language is 0.009px. Three ways to handle it, none free:
 *
 *   - draw true proportions, and seven buckets render as nothing at all;
 *   - floor them and take the pixels from their SIBLINGS, which understates the big buckets;
 *   - floor them and take the pixels from the FREE REMAINDER.
 *
 * The third is what the board draws and what this returns. Every bucket big enough to be drawn
 * to scale IS drawn to scale, no non-empty bucket is ever invisible, and the whole error lands
 * on the grey remainder: the largest quantity on the bar and the least sensitive to drift.
 *
 * WHAT THE BAR THEREFORE SAYS, which is the honest half. It says how full the card is and which
 * buckets exist. It does NOT say how the small buckets compare, because the floored ones all
 * share one width. The Contents table below carries every exact figure and is where a reader
 * compares, which is also why the bar draws no legend: a legend would invite exactly the
 * comparison the widths cannot support.
 *
 * An EMPTY bucket gets no segment. The floor lifts what is small, never what is absent.
 */
export interface SdBarSegment {
  category: string;
  /** Width as a percentage of the whole bar. */
  percent: number;
  /** True when `percent` is the floor rather than this bucket's true share. */
  floored: boolean;
}

export function sdBarSegments(
  bytesByCategory: Readonly<Record<string, number>>,
  order: readonly string[],
  usableBytes: number,
  floorPercent: number,
): SdBarSegment[] {
  if (!(usableBytes > 0)) return [];
  const out: SdBarSegment[] = [];
  for (const category of order) {
    const bytes = bytesByCategory[category] ?? 0;
    if (bytes <= 0) continue; // absent is absent; the floor lifts the small, not the empty
    const truePercent = (bytes / usableBytes) * 100;
    const floored = truePercent < floorPercent;
    out.push({ category, percent: floored ? floorPercent : truePercent, floored });
  }
  return out;
}
